### ISSUE TITLE
Issue : Bug

### ISSUE THREAD

**Issue by yofukashino** [BiltuDas1/no-edge#1]
i have alreayd broke webview and removed edge any help?

**Comment by BiltuDas1** [comment]
Which method you have used? Automatic or Manual

**Comment by yofukashino** [comment]
I removed it using iobit Uninstaller

**Comment by BiltuDas1** [comment]
I think you can change Default Browser from settings then you can port it to other browser like firefox.

**Comment by yofukashino** [comment]
its changed to chrome but i want to install webview and cant install it becoz of that

**Comment by BiltuDas1** [comment]
You wanna Install Webview of MSEdge?

**Comment by yofukashino** [comment]
> You wanna Install Webview of MSEdge?

MicrosoftEdgeWebview2 is what I wanna install and when I try to install it, this is the error I get.
![image](https://user-images.githubusercontent.com/73281112/166568154-a054d5e7-3eee-4afa-a79b-0ce4bf112298.png)

**Comment by BiltuDas1** [comment]
Hey, I think you should uninstall Ms edge. And after that if you install edge then edge will install webview for you.

**Comment by yofukashino** [comment]
> Hey, I think you should uninstall Ms edge. And after that if you install edge then edge will install webview for you. 

It's giving me error too can't install Edge either. Right from phone. Will give you ss of error when I get back.

**Comment by yofukashino** [comment]
![image](https://user-images.githubusercontent.com/73281112/167157286-c794ef6a-75a0-46b6-908f-b2b43e058391.png)
this is the error edge gives me

**Comment by BiltuDas1** [comment]
I think you should Reinstall Operating System

**Comment by yofukashino** [comment]
> I think you should Reinstall Operating System

I don't wanna, any other way possible? else ig I got to stay with this error

**Comment by BiltuDas1** [comment]
Till Now I didn't found any solution.

**Comment by yofukashino** [comment]
Btw I am on windows administrator account if that's to be taken in account.

**Comment by BiltuDas1** [comment]
What do you mean?

**Comment by BiltuDas1** [comment]
> Btw I am on windows administrator account if that's to be taken in account. 

What do you mean?

**Comment by yofukashino** [comment]
![image](https://user-images.githubusercontent.com/73281112/167277190-ca44d282-ed12-4b72-822b-f8735e7d9db1.png)
the windows built in admin account, i am using that

**Comment by yofukashino** [comment]
found out that it was that only, because it was elevating the installer to admin automatically

**Comment by yofukashino** [comment]
thanks for the help, its installed now 💯

**Comment by BiltuDas1** [comment]
> found out that it was that only, because it was elevating the installer to admin automatically

Oh, is it means you run that installer to user so that it worked perfectly?

**Comment by yofukashino** [comment]
> > found out that it was that only, because it was elevating the installer to admin automatically
> 
> Oh, is it means you run that installer to user so that it worked perfectly?

Yeah I disabled it to elevate everything to admin from group policy and it worked
