### ISSUE TITLE
Issue : Bug

### ISSUE THREAD

**Issue by RadNotRed** [BiltuDas1/no-edge#2]
**Describe the bug**
Get's stuck on "Uninstalling Microsoft Edge" 

**Expected behaviour**
It would continue to uninstall microsoft edge

**Screenshots**
![image](https://user-images.githubusercontent.com/80015713/181809013-9b815398-2a99-4f36-b842-ace550816cb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22H2

**Additional context**
Worked on previous versions of windows 11, stopped working on Insider Dev 25169.1000

**Comment by BiltuDas1** [comment]
It actually Happened because Microsoft Patched that, and I already Informed into the readme file that Automatic method will not work. I will try to fix it in future.

**Comment by RadNotRed** [comment]
Oops, i cant read

**Comment by RadNotRed** [comment]
The manual one doesnt work for me either though, it doesn't do anything at command `setup --uninstall --force-uninstall --system-level`

**Comment by BiltuDas1** [comment]
yeah I agree, cuz they patched the whole thing

I trying to fix it

**Comment by BiltuDas1** [comment]
Problem Fixed
