### ISSUE TITLE
Hi 2 questions

### ISSUE THREAD

**Issue by GamerClassN7** [BiltuDas1/no-edge#5]
1) I love zour program but is there way to revert changes to original state ?
2) Just from curiosity how your program exactly works, i noticed there is a middle layiet in terminal or something whitch is shown for few seconds!

Thanks for your amazing work

**Comment by BiltuDas1** [comment]
Q1. What do you mean by revert? Version Revert or, Restoring Microsoft edge like before. If you were talking about restoration of edge to pervious state so that you want to use msedge then you can open cmd.exe(As Administrator) and execute noedge.exe --recovery, It should show all the backups.
Q2. It actually change the location of the files of MSEdge so that it stops function, and replace Patched version of edge, or you can say it replace modified version, it takes parameters (in windows/edge format) and redirect it to default browser. Actually the terminal thing is showing cause I complied it into Visual Studio and I choose the subsystem to Console, That's why it showing console. I didn't remove it cause it helps to switch new parameters, or it shows unknown parameters to the user which as passed through msedge.exe

**Comment by GamerClassN7** [comment]
Q1 it would be wise to write this section to readme and maybe describe to user how it works, since first time your project seemed to mee like some sort of scame and asuerence, by the author taht is is really save did not helped. to that extend that i compiled project my slef to be shure what it does :)
Q2 this is actually weary clever nice !

BTW on each reboot i am getting this erro 
![image](https://user-images.githubusercontent.com/22167469/212824792-f376d242-3f7e-41b2-b7f6-a72dc487120e.png)

**Comment by BiltuDas1** [comment]
Can you show me the debug console, I think the debug console not supposed to be blank.
And I will update all the commands into different markdown file into next release. By the way you can use noedge.exe --help(which is mentioned into the latest release screen) to show what commands are available.

And one question, have you build it from source code?

**Comment by d3aWrVVmn** [comment]
![image](https://user-images.githubusercontent.com/84629487/213169379-f18f2961-3a12-4f4c-bff4-e6bcbb5bbd26.png)
i don't know if it's the same one as @GamerClassN7 's, but i got this one every restart
checked startup items and noticed that there's a new item there
![image](https://user-images.githubusercontent.com/84629487/213169685-f13a7bbb-408f-4169-8bac-31aa3d37c253.png)
disabling that stops it from showing up. still curious about why that startup item is made though

**Comment by BiltuDas1** [comment]
> ![image](https://user-images.githubusercontent.com/84629487/213169379-f18f2961-3a12-4f4c-bff4-e6bcbb5bbd26.png)
> i don't know if it's the same one as @GamerClassN7 's, but i got this one every restart
> checked startup items and noticed that there's a new item there
> ![image](https://user-images.githubusercontent.com/84629487/213169685-f13a7bbb-408f-4169-8bac-31aa3d37c253.png)
> disabling that stops it from showing up. still curious about why that startup item is made though

Oh, I see, It doesn't supposed to be into Startup tab, I didn't implemented anything like this, so that it would run as computer start, I think It actually happening cause Windows want to force setup Edge as Default Browser. I have to investigate over it. By the way thanks for the info.

**Comment by BiltuDas1** [comment]
According to @d3aWrVVmn msedge.exe automatically start at windows, I recently found that it happened cause actual Edge Browser use the technique to speed up browsing speed.

Source: https://www.windowscentral.com/how-prevent-loading-microsoft-edge-processes-startup-windows-10

Okey I will implement a feature in future which will disable that automatically for speeding up pc.

**Comment by BiltuDas1** [comment]
@d3aWrVVmn Can you tell me the registry key name so that I can remove it from registry
the registry key might be located under
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
or
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run

**Comment by d3aWrVVmn** [comment]
Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
with value name MicrosoftEdgeAutoLaunch_CB8B5207BC9E53A7D4BE95E2273959AD
and value data "C:\Program Files(x86)\Microsoft\Edge\Application\msedge.exe" --no-startup-window--win-session-start/prefetch:5
